name: CD

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    concurrency: cd-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.5

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        working-directory: ./client
        run: pnpm install

      - name: Build
        working-directory: ./client
        run: pnpm run build

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SFTP_SERVER }}'
          port: '${{ secrets.SFTP_PORT }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVKEY }} 
          local_path: './client/build/*'
          remote_path: '/var/www/sloodle.alru.xyz'
          args: '-o ConnectTimeout=5'
